### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by Shinigami92** [linterjs/core#15]
# GitHub Actions

## Summary

We should switch from travis to GitHub Actions.

## Motivation

More native support within GitHub.

## Detailed Design

At first we should just migrate our travis file to GitHub Actions.  
We should also update used node versions. (Target LTS = 12 and latest = 14).
Maybe we can also add a badge that represent the latest build status.

## Documentation

Maybe? In a wiki?

## Drawbacks

Dont think so.

## Alternatives

We could stay at travis, but why?

## Open Questions

We maybe need to think about coverage steps and uploading artefacts.

## Help Needed

I have already collected some experience with GitHub Actions 🙂

## Frequently Asked Questions

Currently none

## Related Discussions

Currently none

**Comment by Shinigami92** [comment]
I'm not into `appveyor`, can this also be removed?

**Comment by zimme** [comment]
Appveyor is used to run test on windows, but it seems as though GitHub Actions support windows unless I'm mistaken.

For my personal projects I'm working on moving them over to GitLab. I just prefer to use open-source products whenever there are alternatives that are as good as non open-source products and I feel GitLab has caught up with GitHub.

Not as this project isn't under my account and under an organization I'm fine with keeping it here on GitHub and with that said I guess it would be ok to use GitHub Actions instead of Travis. Just consider that it will require more work if this project will move away from GitHub in the future, but if you're fine with that I have no objections.

**Comment by Shinigami92** [comment]
I'm working with GitLab at work and I would love to stay at **GitHub** with this project (OpenSource projects)
It has a much greater open source community and keep up with features like actions and so on.
GitHub is currently adding many more features as before some years 🙂
